#! /usr/bin/env sh
#
# Saas (Shell-as-a-Service) based on https://github.com/cmj0121/ptool/shell
# This shell-script provide to scan the target by IP/Hostname

nmap -O -A {{ . }}
nmap -sU --top-ports 15 {{ . }}
