name: ci_cd

on:
  - push


jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    name: build/push docker image

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: login registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: git tag
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GIHBUT_REF | cut -d / -f 3)
      - name: push
        run: TAG=TAG make push
        if: ${{ github.ref == 'ref/head/v*' }}
