name: ci_cd
description: the CI/CD via the GitHub Action

on:
  - push


jobs:
  build_image:
    runs-on: ubuntu-latest
    name: build docker image

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: login registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secret.GHCR_TOKEN }}
      - name: git tag
        id: tag
        run: echo ::set-output name=VERSION::$(echo $GIHBUT_REF | cud -d / -f 3)
